version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring_app:
    image: soufi2001/devopsback:5arctic3-g4-devops
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root  
      SPRING_ALLOW_EMPTY_PASSWORD: "yes"
      # Add any other environment variables your Spring Boot application requires
    ports:
      - "8082:8082"
    networks:
      - app_network

  angular_app:
    image: soufi2001/devopsfront:5arctic3-g4-devops
    depends_on:
      - spring_app
    ports:
      - "4200:80"  # default for Angular CLI server
    environment:
      API_URL: http://spring_app:8080  # Ensure the Angular app points to the Spring API
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
