global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: '/prometheus'  # Path Jenkins exposes metrics on
    static_configs:
      - targets: ['172.18.0.1:8080']  # Jenkins address


  - job_name: 'nexus'
    metrics_path: '/service/metrics'  # Path to the Nexus metrics
    static_configs:
      - targets: ['nexus:8081']  # Nexus service name and port



  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'  # Correct metrics path
    static_configs:
      - targets: ['springboot:8082']  # Use the service name and internal port
